description: RHUI CDS-1 Server
hostname: &hostname cds-1
fqdn: &fqdn cds-1.m2.local
ip: &ip 192.168.155.21
interfaces:
  - device: eth0
    mac: "52:54:00:05:00:21"
    ip: *ip
    host: *hostname
    fqdn: *fqdn
    network: service

kscfg: rhui-cds-ks.cfg

disks:
  - src: default
    size: 50

setup_data:
  - src: data/rhua/Makefile
    dst: Makefile


