description: RHUA Server
hostname: &hostname rhua
fqdn: &fqdn rhua.m2.local
ip: &ip 192.168.155.20
interfaces:
  - device: eth0
    mac: "52:54:00:05:00:20"
    ip: *ip
    host: *hostname
    fqdn: *fqdn
    network: service

kscfg: rhua-ks.cfg

cdsservers:
  - name: cds-1
    fqdn: cds-1.m2.local
  - name: cds-2
    fqdn: cds-2.m2.local

cert:
  key_length: 2048
  expiration_dates: 1095
  subject: "/C=JP/O=M2 Example, Inc./CN="

disks:
  - src: default
    size: 50
