description: RHN Satellite server
hostname: &hostname satellite
fqdn: &fqdn satellite.m2.local
ip: &ip 192.168.155.10
interfaces:
  - device: eth0
    mac: "52:54:00:05:00:10"
    ip: *ip
    host: *hostname
    fqdn: *fqdn
    network: service

kscfg: satellite-ks.cfg

disks:
  - src: default
    size: 50

satellite:
  admin:
    email: root@localhost

  ssl:
    org: "M2 Example, Inc."
    unit: "IT Dept."
    city: Shibuya-ku
    state: Tokyo
    country: JP
    password: sslsecret

rhn:
#  username: foo@m2.local
#  password: xyzsecret

proxy:
#  fqdn: proxy.m2.local
#  username: proxyuser
#  username: proxypasswd
