common:
  autopart: true
  rhui_network_1: &rhui_network_1 192.168.20.0  # see 10_networks.yml

  rhui:
    # example: 54fb6627dbaa37721048e4549db3224d.pem
    rhui_entitlement_cert: &rhui_entitlement_cert YOUR_RHUI_ENTITLEMNET_CERT_0

    ssl_cert_subject: &ssl_cert_subject "/C=JP/ST=Tokyo/O=Example, Inc./CN="

    rhua:
      ip: &rhua_ip 192.168.20.11
      fqdn: &rhua_fqdn rhua-1.example.com
      hostname: &rhua_hostname rhua-1
      cds_cluster: &cds_cluster cds_cluster_1

    cds-1:
      ip: &cds_1_ip 192.168.20.21
      fqdn: &cds_1_fqdn cds-1.example.com
      cli_fqdn: *cds_1_fqdn
      hostname: &cds_1_hostname cds-1

    cds-2:
      ip: &cds_2_ip 192.168.20.22
      fqdn: &cds_2_fqdn cds-2.example.com
      cli_fqdn: *cds_2_fqdn
      hostname: &cds_2_hostname cds-2

  hosts: &hosts
    # RHUA:
    - ip: *rhua_ip
      fqdn: *rhua_fqdn
      hostname: *rhua_hostname

    # CDS 1:
    - ip: *cds_1_ip
      fqdn: *cds_1_fqdn
      hostname: *cds_1_hostname

    # CDS 2:
    - ip: *cds_2_ip
      fqdn: *cds_2_fqdn
      hostname: *cds_2_hostname

  rhn:
    account: YOUR_RHN_ACCOUNT

  gpg:
    passpharase: secret

  test:
    # change DNS server addresses to gateway's one:
    #mod_for_test_env: "sed -e 's,ks.cfg,test.ks.cfg,g'

guests:
  - name: rhua
    description: RHUA server

    cert:
      key_length: 2048
      expiration_dates: 3650
      subject: *ssl_cert_subject

    rhui_entitlement_certs:
      - *rhui_entitlement_cert

    templates:
      autoinst:
        src: autoinstall.d/rhua-ks.cfg

    setup_data:
      - src: data/rhui/rhua/answers.txt
        dst: answers.txt
      - src: data/rhui/rhua/Makefile
        dst: Makefile
      - src: data/rhui/rhua/Makefile.certs
        dst: certs/Makefile
      - src: data/rhui/rhua/gen_rpm_gpgkey.sh
        dst: gen_rpm_gpgkey.sh
      - src: data/rhui/rhua/gen_ssl_server.sh
        dst: gen_ssl_server.sh
      - src: *rhui_entitlement_cert

    cds:
      cluster: *cds_cluster

    cdsservers:
      - name: *cds_1_hostname
        fqdn: *cds_1_fqdn
        cluster: *cds_cluster
      - name: *cds_2_hostname
        fqdn: *cds_2_fqdn
        cluster: *cds_cluster

    guests:
      - name: rhua
        hostname: *rhua_hostname
        ip: *rhua_ip
        interfaces:
          - network: *rhui_network_1
            bootproto: static
            options: --activate

        virtinst:
          extra_args: ip=192.168.20.11 netmask=255.255.255.0

  - name: cds
    description: RHUI CDS Server

    templates:
      autoinst:
        src: autoinstall.d/rhui-cds-ks.cfg

    setup_data:
      - src: data/rhui/cds/Makefile
        dst: Makefile

    guests:
      - hostname: *cds_1_hostname
        name: cds-1
        ip: *cds_1_ip
        interfaces:
          - network: *rhui_network_1
            bootproto: static
            options: --activate

        virtinst:
          extra_args: ip=192.168.20.21 netmask=255.255.255.0

      - hostname: *cds_2_hostname
        name: cds-2
        ip: *cds_2_ip
        interfaces:
          - network: *rhui_network_1
            bootproto: static
            options: --activate

        virtinst:
          extra_args: ip=192.168.20.22 netmask=255.255.255.0

  - name: rhel-6-rhui-client
    description: RHEL 6 client systems using CCP subscriptions
    templates:
      autoinst:
        src: autoinstall.d/rhel-6-rhui-client-ks.cfg

    disks:
      - pool: default
        format: qcow2
        cache: none
        size: 6
        bus: scsi

    guests:
      - hostname: rhel-6-rhui-client-1
        interfaces:
          - network: *rhui_network_1
            bootproto: dhcp

  - name: rhel-5-rhui-client
    description: RHEL 5 client systems using CCP subscriptions

    filesystem: ext3
    virtinst:
      location: http://192.168.20.254/kstree/rhel-5.10-x86_64/
      os_variant: rhel5.4

    disks:
      - pool: default
        format: qcow2
        cache: none
        size: 6
        bus: virtio

    partition: |
      part /boot --asprimary --fstype="ext3" --size=200
      part /     --asprimary --fstype="ext3" --size=1 --grow
      part swap  --fstype="swap" --size=1024
    templates:
      autoinst:
        src: autoinstall.d/rhel-5-rhui-client-ks.cfg

    guests:
      - hostname: rhel-5-rhui-client-1
        interfaces:
          - network: *rhui_network_1
            bootproto: dhcp

# vim:sw=2:ts=2:et:
